Feature/change password
tomnisim/ScooterGotcha pull request #108
Opened 2023-04-12 10:44 UTC by sashajke

2023-04-17 06:30 UTC, amitmosk requested changes

2023-04-17 06:30 UTC, amitmosk commented on server/src/main/java/gotcha/server/Service/Facade.java
Add TODO to line 326 : change for configuration data

2023-04-17 06:30 UTC, amitmosk commented on server/src/main/java/gotcha/server/Utils/Utils.java
minLength & maxLength should be set by configuration

2023-04-18 13:18 UTC, sashajke commented on server/src/main/java/gotcha/server/Utils/Utils.java
done

2023-04-18 13:18 UTC, sashajke commented on server/src/main/java/gotcha/server/Service/Facade.java
done

2023-04-18 16:21 UTC, amitmosk approved these changes

2023-04-18 16:21 UTC, merged